# Generated by Django 3.0.8 on 2021-04-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Rent_or_Buy',
            field=models.CharField(choices=[('1', 'Rent'), ('1', 'Buy')], default='', max_length=10),
        ),
    ]
