# Generated by Django 3.0.8 on 2021-04-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_post_rent_or_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Rent_or_Buy',
            field=models.CharField(choices=[('1', 'Rent'), ('2', 'Buy')], default='', max_length=10),
        ),
    ]
