# Generated by Django 3.2 on 2021-05-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20210430_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Rent_or_Buy',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='houses.post')),
            ],
        ),
    ]
