# Generated by Django 3.2 on 2021-05-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20210507_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Descriptions',
            field=models.CharField(default='elezea kuhusu nyumba', max_length=900),
        ),
    ]
