# Generated by Django 3.2 on 2021-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_post_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
