# Generated by Django 3.2 on 2021-05-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_auto_20210509_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='1.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='1.jpg', upload_to='pics'),
        ),
    ]
